name: Build Cordova APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Install Cordova
      run: npm install -g cordova
      
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Build APK
      run: |
        cordova create myapp com.terrible.khata "Khata App"
        
        # 🟢 THE MAGIC FIX 1: Tuhada custom config overwrite karega default nu
        cp config.xml myapp/config.xml
        
        rm -rf myapp/www/*
        rsync -a ./www/ myapp/www/

        cd myapp
        
        # 🟢 THE MAGIC FIX 2: Android version 13 pao
        cordova platform add android@13
        
        # Zaroori Plugins
        cordova plugin add cordova-plugin-androidx-adapter
        cordova plugin add cordova-plugin-contacts
        cordova plugin add cordova-plugin-dialogs
        cordova plugin add cordova-plugin-fingerprint-aio
        cordova plugin add cordova-plugin-local-notification
        cordova plugin add cordova-plugin-x-socialsharing
        cordova plugin add cordova-plugin-file
        cordova plugin add cordova-plugin-file-opener2
        cordova plugin add cordova-plugin-camera
        cordova plugin add cordova-plugin-zip
        cordova build android --debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: KhataApp-APK
        path: "**/app-debug.apk"
